export const USER_CONNECTED = "USER_CONNECTED";
export const USER_DISCONNECTED = "USER_DISCONNECTED";
export const TEXT_MESSAGE = "TEXT_MESSAGE";
export const IMAGE_MESSAGE = "IMAGE_MESSAGE";
export const AUDIO_MESSAGE = "AUDIO_MESSAGE";
export const VIDEO_MESSAGE = "VIDEO_MESSAGE";
export const ACTIVE_USERS_MESSAGE = "ACTIVE_USERS";
