export const USER_JOINED = 'USER_JOINED';
export const USER_LEFT = 'USER_LEFT';

export const TEXT_MESSAGE = 'TEXT_MESSAGE';
export const IMAGE_MESSAGE = 'IMAGE_MESSAGE';
export const AUDIO_MESSAGE = 'AUDIO_MESSAGE';
export const VIDEO_MESSAGE = 'VIDEO_MESSAGE';
export const PDF_MESSAGE = 'PDF_MESSAGE';
export const TEXT_DOC_MESSAGE = 'TEXT_DOC_MESSAGE';

export const ACTIVE_USERS_MESSAGE = 'ACTIVE_USERS';
export const SERVER_INFO_MESSAGE = 'SERVER_INFO';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const GET_HISTORY_MESSAGE = 'GET_HISTORY';
export const PING_MESSAGE = 'PING';
export const PONG_MESSAGE = 'PONG';

export const USER_MESSAGES = [
  TEXT_MESSAGE, IMAGE_MESSAGE, AUDIO_MESSAGE,
  VIDEO_MESSAGE, PDF_MESSAGE, TEXT_DOC_MESSAGE,
];
