export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
export const USER_TYPING = 'USER_TYPING';
export const USER_STOPPED_TYPING = 'USER_STOPPED_TYPING';

export const USER_JOINED = 'USER_JOINED';
export const USER_LEFT = 'USER_LEFT';

export const TEXT_MESSAGE = 'TEXT_MESSAGE';
export const IMAGE_MESSAGE = 'IMAGE_MESSAGE';
export const AUDIO_MESSAGE = 'AUDIO_MESSAGE';
export const VIDEO_MESSAGE = 'VIDEO_MESSAGE';
export const PDF_MESSAGE = 'PDF_MESSAGE';
export const TEXT_DOC_MESSAGE = 'TEXT_DOC_MESSAGE';

export const MENTION_MESSAGE = 'MENTION_MESSAGE';
export const COMMAND_RESPONSE = 'COMMAND_RESPONSE';

export const ACTIVE_USERS_MESSAGE = 'ACTIVE_USERS';
export const INFO_MESSAGE = 'INFO_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';
export const GET_HISTORY_MESSAGE = 'GET_HISTORY';
export const PING_MESSAGE = 'PING';
export const PONG_MESSAGE = 'PONG';
export const RESTART_MESSAGE = 'RESTART';
export const MAINTENANCE_MESSAGE = 'MAINTENANCE';
export const TOO_FAST_MESSAGE = 'TOO_FAST';
export const BADGE_EARNED_MESSAGE = 'BADGE_EARNED';

export const USER_MESSAGES = [
  TEXT_MESSAGE, IMAGE_MESSAGE, AUDIO_MESSAGE,
  VIDEO_MESSAGE, PDF_MESSAGE, TEXT_DOC_MESSAGE,
];
